### ISSUE TITLE
Missing SOTA comparisions and paper references to add

### ISSUE THREAD

**Issue by wgcban** [f64051041/SARAS-Net#1]
Hi,

I like your work, and thanks for making the code available to the researchers.

However, your method does not compare with recent state-of-the-art change detection methods like [`ChangeFormer`](https://github.com/wgcban/ChangeFormer)and [`DDPM-CD`](https://github.com/wgcban/ddpm-cd).

At least you do not mention there exists such works in the related works. 

Any reason for this?

**Comment by f64051041** [comment]
Thanks for your comments. We think ChangeFormer and DDPM-CD have done great jobs. In future work, we will refer to these methods.
